### ISSUE TITLE
Storing IPs in sqlite3

### ISSUE THREAD

**Issue by hbfs** [jinzhu/gorm#1092]
from the "net" standard library IPv4/v6 are stored as []byte.

https://github.com/jinzhu/gorm/blob/master/dialect_sqlite3.go#L58 should be a match, but I'm getting a panic

```
panic: invalid sql type IP (slice) for sqlite3

goroutine 1 [running]:
panic(0x4719940, 0xc82000b5d0)
    /usr/local/opt/go/libexec/src/runtime/panic.go:481 +0x3e6
github.com/jinzhu/gorm.sqlite3.DataTypeOf(0xc820257130, 0x0, 0xc8201ea820, 0x0, 0x0)
    /gopath/src/github.com/jinzhu/gorm/dialect_sqlite3.go:65 +0x394
github.com/jinzhu/gorm.(*sqlite3).DataTypeOf(0xc8202ef670, 0xc8201ea820, 0x0, 0x0)
    <autogenerated>:102 +0xae
github.com/jinzhu/gorm.(*Scope).createTable(0xc8202b1300, 0xc82000a448)
    /gopath/src/github.com/jinzhu/gorm/scope.go:1067 +0x13e
github.com/jinzhu/gorm.(*Scope).autoMigrate(0xc8202b1300, 0x46ea620)
    /gopath/src/github.com/jinzhu/gorm/scope.go:1146 +0x110
github.com/jinzhu/gorm.(*DB).AutoMigrate(0xc82030cc80, 0xc8201d3e80, 0x1, 0x1, 0xc8202d9dd0)
    /gopath/src/github.com/jinzhu/gorm/main.go:525 +0xb1
main.main()
    /Projects/go/main.go:107 +0x15d
exit status 2
```

**Comment by jinzhu** [comment]
related to https://github.com/jinzhu/gorm/pull/1420
