### ISSUE TITLE
how to create slice data?

### ISSUE THREAD

**Issue by btfak** [jinzhu/gorm#1162]
I have a slice insert like  
```
var data []model
db.Table.("table").Create(&data)
```
but i get 
```
panic: reflect: call of reflect.Value.Interface on zero Value

goroutine 1 [running]:
reflect.valueInterface(0x0, 0x0, 0x0, 0x35b201, 0x0, 0x0)
       	/usr/local/Cellar/go/1.5.1/libexec/src/reflect/value.go:906 +0x7f
reflect.Value.Interface(0x0, 0x0, 0x0, 0x0, 0x0)
       	/usr/local/Cellar/go/1.5.1/libexec/src/reflect/value.go:901 +0x48
github.com/jinzhu/gorm.createCallback(0xc82019d600)
       	/Users/long/gopath/src/github.com/jinzhu/gorm/callback_create.go:58 +0x159f
github.com/jinzhu/gorm.(*Scope).callCallbacks(0xc82019d600, 0xc82019cb80, 0x9, 0x10, 0x5)
       	/Users/long/gopath/src/github.com/jinzhu/gorm/scope.go:808 +0x68
github.com/jinzhu/gorm.(*DB).Create(0xc82088b220, 0x339740, 0xc82065e980, 0xc82088b220)
       	/Users/long/gopath/src/github.com/jinzhu/gorm/main.go:375 +0x7a
gitlab.com/btfak/spider/server.getDetail()
```

**Comment by danhardman** [comment]
```go
for _, model := range data {
 db.Create(&model)
}
```
