### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by tboerger** [jinzhu/gorm#1164]
I'm not sure if this is an issue or just my problem. Can somebody tell me what's wrong?

```
# go run main.go
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x40 pc=0x409c9dd]

goroutine 1 [running]:
panic(0x42b3a20, 0xc82000a140)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:464 +0x3e6
github.com/jinzhu/gorm.(*Scope).related(0x0, 0x425dd40, 0xc82034d7a0, 0xc8203f47c0, 0x1, 0x1, 0x0)
	/Users/thomas/Developer/golang/src/github.com/jinzhu/gorm/scope.go:972 +0x4d
github.com/jinzhu/gorm.(*Association).Find(0xc8203db920, 0x425dd40, 0xc82034d7a0, 0xc8203db920)
	/Users/thomas/Developer/golang/src/github.com/jinzhu/gorm/association.go:19 +0xc1
main.main()
	/Users/thomas/Developer/golang/src/github.com/testing/testing/main.go:68 +0x7b9
exit status 2
```

```
package main

import (
	"log"

	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/sqlite"
)

type Teams []*Team

type Team struct {
	ID        int       `json:"id" gorm:"primary_key"`
	Name      string    `json:"name"`
	Users     Users     `json:"users,omitempty" gorm:"many2many:team_users;"`
	TeamUsers TeamUsers `json:"team_users,omitempty"`
}

type Users []*User

type User struct {
	ID        int       `json:"id" gorm:"primary_key"`
	Name      string    `json:"name"`
	Teams     Teams     `json:"teams,omitempty" gorm:"many2many:team_users;"`
	TeamUsers TeamUsers `json:"team_users,omitempty"`
}

type TeamUsers []*TeamUser

type TeamUser struct {
	Team *Team  `json:"team,omitempty"`
	User *User  `json:"user,omitempty"`
	Perm string `json:"perm,omitempty"`
}

func main() {
	db, err1 := gorm.Open("sqlite3", "testing.db")

	if err1 != nil {
		log.Fatal(err1)
	}

	defer db.Close()

	db.DropTableIfExists(&User{}, &Team{}, &TeamUser{})
	db.AutoMigrate(&User{}, &Team{}, &TeamUser{})

	user := &User{
		Name: "user",
	}

	db.Create(user)

	team := &Team{
		Name: "team",
	}

	db.Create(team)

	records := &TeamUsers{}

	err2 := db.Model(
		team,
	).Association(
		"TeamUsers",
	).Find(
		records,
	).Error

	if err2 != nil {
		log.Fatal(err2)
	}

	log.Printf("%+v", records)
}
```

**Comment by tboerger** [comment]
Maybe I should mention that I try to fetch `TeamUser` because the many to many table got an additional column.

**Comment by tboerger** [comment]
Ok, maybe this is easier to retrieve the result...

```
	err := db.Where(
		"team_id = ?",
		team.ID,
	).Model(
		&model.TeamUser{},
	).Preload(
		"Team",
	).Preload(
		"User",
	).Find(
		records,
	).Error
```

**Comment by danhardman** [comment]
I think `TeamUsers` should be of type `[]TeamUser`, not `[]*TeamUser`.

**Comment by jinzhu** [comment]
`TeamUser` missing foreign key

```go
type TeamUser struct {
	Team   *Team `json:"team,omitempty"`
	User   *User `json:"user,omitempty"`
	UserID int
	TeamID int
	Perm   string `json:"perm,omitempty"`
}
```
