### ISSUE TITLE
panic

### ISSUE THREAD

**Issue by spx** [jinzhu/gorm#1175]
panic: interface conversion: interface is nil, not gorm.logger

goroutine 38 [running]:
panic(0x3c61a0, 0xc4201c7300)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/jinzhu/gorm.(*DB).print(0xc420256000, 0xc4202302c0, 0x2, 0x2)
	/Users/mindaugas/gocode/src/github.com/jinzhu/gorm/main.go:690 +0x64
created by github.com/jinzhu/gorm.(*DB).AddError
	/Users/mindaugas/gocode/src/github.com/jinzhu/gorm/main.go:641 +0x174
exit status 2

https://play.golang.org/p/4tFuDw2iia

**Comment by spx** [comment]
shadow variables...
