### ISSUE TITLE
Many-to-Many panic with AssociationForeignKey or ForeignKey

### ISSUE THREAD

**Issue by pedorich-n** [jinzhu/gorm#1331]
I have structs PaymentTerm and BillingGroup:
```
type PaymentTerm struct {
	ID    int64  `gorm:"primary_key"`
	Value string `gorm:"type:varchar(20)"`
}

type GormBillingGroup struct {
	ID             int64     `gorm:"primary_key"`
         ...
	//Aggregated field
	PTerms     []PaymentTerm  `gorm:"many2many:billing_groups_payment_terms;"`
}
```

As you can see BillingGroup starts with Gorm this is because I'm moving from MongoDB, and I don't want to break old models until I move completely.
In DB I have join table:
```
CREATE TABLE "billing_groups_payment_terms" (
	"billing_group_id" bigint NOT NULL,
	"payment_term_id" bigint NOT NULL,
	CONSTRAINT billing_groups_payment_terms_pk PRIMARY KEY ("billing_group_id","payment_term_id")
)
```
I'm fetching data like this:
```
db.Model(&GormBillingGroup{}).Association("PTerms").Find(&terms)
```
Which turns in this SQL code:
```
SELECT "payment_terms".* FROM "payment_terms" 
INNER JOIN "billing_groups_payment_terms" 
ON "billing_groups_payment_terms"."payment_term_id" = "payment_terms"."id" 
WHERE ("billing_groups_payment_terms"."gorm_billing_group_id" IN ('1'))
```

As you can see GORM converts struct name and bypassing TableName() which I overwrote, but if I'll write tags `AssociationForeignKey:payment_term_id;ForeignKey:billing_group_id`, or at least one of them I'll get panic:
```
runtime error: invalid memory address or nil pointer dereference goroutine 18 [running]:
/usr/local/go/src/runtime/panic.go:458 +0x243
*path*/vendor/github.com/jinzhu/gorm.(*Scope).related(0x0, 0xa459e0, 0xc4203a00c0, 0xc4203ce190, 0x1, 0x1, 0xb50460)
*path*/vendor/github.com/jinzhu/gorm/scope.go:994 +0x55
*path*/vendor/github.com/jinzhu/gorm.(*Association).Find(0xc4203cc300, 0xa459e0, 0xc4203a00c0, 0xc4203cc300)
```
So for now as workaround I just changed column name in my DB

**Comment by pedorich-n** [comment]
Also, fetching with `Relation()` and tags creates this sql
```
SELECT "payment_terms".* FROM "payment_terms" INNER JOIN "billing_groups_payment_terms" ON  WHERE (1 <> 1)
```
