### ISSUE TITLE
invalid sql type StringArray (slice) for postgres

### ISSUE THREAD

**Issue by nri-pl** [jinzhu/gorm#1454]
### What version of Go are you using (`go version`)?
1.8.1

### Which database and its version are you using?
postgresql 9.6

### What did you do?

Please provide a complete runnable program to reproduce your issue.

```go
package main

import (
	"github.com/jinzhu/gorm"
	"github.com/lib/pq"
	"log"
)

func main() {
	db, err := gorm.Open("postgres", "user=lw dbname=kk sslmode=disable")
	if err != nil {
		log.Panic(err)
	}
	db.AutoMigrate(&Test{})
}

type Test struct {
	ID   uint64         `gorm:"primary_key"`
	Tags pq.StringArray `gorm:"type:varchar(100)[]`
}

```
Output:
```
panic: invalid sql type StringArray (slice) for postgres

goroutine 1 [running]:
github.com/jinzhu/gorm.(*postgres).DataTypeOf(0xc420139e40, 0xc420070ea0, 0x0, 0x0)
	/go/src/github.com/jinzhu/gorm/dialect_postgres.go:77 +0x425
github.com/jinzhu/gorm.(*Scope).createTable(0xc420141500, 0xc420143180)
	/go/src/github.com/jinzhu/gorm/scope.go:1097 +0x2e2
github.com/jinzhu/gorm.(*Scope).autoMigrate(0xc420141500, 0x695ee0)
	/go/src/github.com/jinzhu/gorm/scope.go:1176 +0x3e4
github.com/jinzhu/gorm.(*DB).AutoMigrate(0xc42016a000, 0xc42014bf48, 0x1, 0x1, 0x1)
	/go/src/github.com/jinzhu/gorm/main.go:557 +0x77
main.main()
	/main.go:14 +0x198

```
Hi,
It seems to me that it should work.
What am I doing wrong?
#1248

**Comment by nri-pl** [comment]
Tags pq.StringArray `gorm:"type:varchar(100)[]`
Tags pq.StringArray `gorm:"type:varchar(100)[]"`
