### ISSUE TITLE
The ability to disable built-in transactions for insert (and other) queries

### ISSUE THREAD

**Issue by MOZGIII** [jinzhu/gorm#1699]
### What version of Go are you using (`go version`)?
go version go1.9 linux/amd64

### Which database and its version are you using?
postgres (PostgreSQL) 10.0

### What did you do?

I've manually opened transaction and inserted a row via gorm.
Gorm commited my transaction, which I didn't want to happen.

```go
package main

import (
	"fmt"

	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/postgres"
)

var db *gorm.DB

// A is just a demo table.
type A struct{ Val string }

func init() {
	var err error
	// db, err = gorm.Open("postgres", "postgres://postgres:postgres@localhost?sslmode=disable")
	db, err = gorm.Open("postgres", "user=gorm dbname=gorm sslmode=disable")
	if err != nil {
		panic(err)
	}
	db.LogMode(true)
}

func main() {
	panicOnDBErr(db.DropTableIfExists(&A{}))
	panicOnDBErr(db.AutoMigrate(&A{}))

	panicOnDBErr(db.Begin())

	panicOnDBErr(db.Create(&A{"test"}))

	panicOnDBErr(db.Rollback()) // panic here

	var list []A
	panicOnDBErr(db.Find(&list))

	fmt.Println(&list)
}

func panicOnDBErr(db *gorm.DB) {
	panicOnErr(db.Error)
}

func panicOnErr(err error) {
	if err != nil {
		panic(err)
	}
}
```

Output:
```
(/go/src/testtt/main.go:26) 
[2017-12-02 14:30:56]  [49.42ms]  DROP TABLE "as"  
[0 rows affected or returned ] 

(/go/src/testtt/main.go:27) 
[2017-12-02 14:30:56]  [40.77ms]  CREATE TABLE "as" ("val" text )   
[0 rows affected or returned ] 

(/go/src/testtt/main.go:31) 
[2017-12-02 14:30:56]  [0.51ms]  INSERT INTO "as" ("val") VALUES ('test') RETURNING "as".*  
[1 rows affected or returned ] 

(/go/src/testtt/main.go:33) 
[2017-12-02 14:30:56]  no valid transaction 
panic: no valid transaction

goroutine 1 [running]:
main.panicOnErr(0x850c20, 0xc4201324e0)
	/go/src/testtt/main.go:47 +0x4a
main.panicOnDBErr(0xc420180000)
	/go/src/testtt/main.go:42 +0x38
main.main()
	/go/src/testtt/main.go:33 +0x1a8
exit status 2
```

DB log:
```
2017-12-02 11:26:42.267 UTC [49] LOG:  execute <unnamed>: SELECT count(*) FROM INFORMATION_SCHEMA.tables WHERE table_name = $1 AND table_type = 'BASE TABLE' AND table_schema = CURRENT_SCHEMA()
2017-12-02 11:26:42.267 UTC [49] DETAIL:  parameters: $1 = 'as'
2017-12-02 11:26:42.267 UTC [49] LOG:  statement: DROP TABLE "as"
2017-12-02 11:26:42.279 UTC [49] LOG:  execute <unnamed>: SELECT count(*) FROM INFORMATION_SCHEMA.tables WHERE table_name = $1 AND table_type = 'BASE TABLE' AND table_schema = CURRENT_SCHEMA()
2017-12-02 11:26:42.279 UTC [49] DETAIL:  parameters: $1 = 'as'
2017-12-02 11:26:42.279 UTC [49] LOG:  statement: CREATE TABLE "as" ("val" text ) 
2017-12-02 11:26:42.315 UTC [49] LOG:  statement: BEGIN READ WRITE
2017-12-02 11:26:42.316 UTC [50] LOG:  statement: BEGIN READ WRITE
2017-12-02 11:26:42.317 UTC [50] LOG:  execute <unnamed>: INSERT INTO "as" ("val") VALUES ($1) RETURNING "as".*
2017-12-02 11:26:42.317 UTC [50] DETAIL:  parameters: $1 = 'test'
2017-12-02 11:26:42.317 UTC [50] LOG:  statement: COMMIT
2017-12-02 11:26:42.346 UTC [49] LOG:  unexpected EOF on client connection with an open transaction
2017-12-02 11:30:56.167 UTC [55] LOG:  execute <unnamed>: SELECT count(*) FROM INFORMATION_SCHEMA.tables WHERE table_name = $1 AND table_type = 'BASE TABLE' AND table_schema = CURRENT_SCHEMA()
2017-12-02 11:30:56.167 UTC [55] DETAIL:  parameters: $1 = 'as'
2017-12-02 11:30:56.167 UTC [55] LOG:  statement: DROP TABLE "as"
2017-12-02 11:30:56.218 UTC [55] LOG:  execute <unnamed>: SELECT count(*) FROM INFORMATION_SCHEMA.tables WHERE table_name = $1 AND table_type = 'BASE TABLE' AND table_schema = CURRENT_SCHEMA()
2017-12-02 11:30:56.218 UTC [55] DETAIL:  parameters: $1 = 'as'
2017-12-02 11:30:56.218 UTC [55] LOG:  statement: CREATE TABLE "as" ("val" text ) 
2017-12-02 11:30:56.259 UTC [55] LOG:  statement: BEGIN READ WRITE
2017-12-02 11:30:56.263 UTC [56] LOG:  statement: BEGIN READ WRITE
2017-12-02 11:30:56.270 UTC [56] LOG:  execute <unnamed>: INSERT INTO "as" ("val") VALUES ($1) RETURNING "as".*
2017-12-02 11:30:56.270 UTC [56] DETAIL:  parameters: $1 = 'test'
2017-12-02 11:30:56.270 UTC [56] LOG:  statement: COMMIT
2017-12-02 11:30:56.297 UTC [55] LOG:  unexpected EOF on client connection with an open transaction
```
Notice there are two `BEGIN READ WRITE` there.

I just want to manage transactions manually. Currently system is completely broken if you combine manually managed transactions and gorm's insert/update/delete.

How can this be fixed? Discuss?

**Comment by MOZGIII** [comment]
Oh, yes. It's my bad. You have to chain all nested calls from db value returnex from `db.Begin()`.
