### ISSUE TITLE
Fails to automigrate structs with scanner fields

### ISSUE THREAD

**Issue by Vany** [jinzhu/gorm#1771]
### What version of Go are you using (`go version`)?
1.9.4

### Which database and its version are you using?
pg 9.6

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**
```
package main

import (
	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/postgres"
	_ "github.com/lib/pq"
	_ "github.com/lib/pq/hstore"

)

type X struct {
	Id int `gorm:"primary_key"`
	Name string
	Y Y `gorm:"type:json"`
}

type Y struct {
}

func (m *Y) Scan(b interface{}) error {
	return nil
}


func main() {
	Db, _ := gorm.Open("postgres", "host=192.168.1.69 user=masternodes dbname=mn sslmode=disable password=masternodes")
	Db.AutoMigrate(&X{})
}
```

### error
```
GOROOT=C:\Go #gosetup
GOPATH=C:\box\go #gosetup
C:\Go\bin\go.exe build -i -o C:\Users\vany\AppData\Local\Temp\___go_build_trygorm_go.exe C:/box/go/src/gogs.visteras.ru/pool/masternodes/test/trygorm.go #gosetup
"C:\Program Files\JetBrains\GoLand 2017.3\bin\runnerw.exe" C:\Users\vany\AppData\Local\Temp\___go_build_trygorm_go.exe #gosetup
panic: reflect: Field index out of range

goroutine 1 [running]:
reflect.Value.Field(0x6b7b20, 0x882028, 0x199, 0x0, 0x882028, 0x882001, 0x16)
	C:/Go/src/reflect/value.go:769 +0x153
gogs.visteras.ru/pool/masternodes/vendor/github.com/jinzhu/gorm.ParseFieldStructForDialect.func1(0x6b7b20, 0x882028, 0x199)
	C:/box/go/src/gogs.visteras.ru/pool/masternodes/vendor/github.com/jinzhu/gorm/dialect.go:81 +0x12a
gogs.visteras.ru/pool/masternodes/vendor/github.com/jinzhu/gorm.ParseFieldStructForDialect(0xc042080a90, 0x6b7b20, 0x882028, 0x199, 0x444641, 0x10, 0x0, 0xc04206db00, 0xc042126b00)
	C:/box/go/src/gogs.visteras.ru/pool/masternodes/vendor/github.com/jinzhu/gorm/dialect.go:84 +0x170
gogs.visteras.ru/pool/masternodes/vendor/github.com/jinzhu/gorm.postgres.DataTypeOf(0xc042119900, 0xc042080a90, 0xc042132da0, 0xb)
	C:/box/go/src/gogs.visteras.ru/pool/masternodes/vendor/github.com/jinzhu/gorm/dialect_postgres.go:27 +0x4a
gogs.visteras.ru/pool/masternodes/vendor/github.com/jinzhu/gorm.(*postgres).DataTypeOf(0xc042070b30, 0xc042080a90, 0x1, 0x1)
	<autogenerated>:1 +0x4d
gogs.visteras.ru/pool/masternodes/vendor/github.com/jinzhu/gorm.(*Scope).createTable(0xc04212de00, 0xc0421269e8)
	C:/box/go/src/gogs.visteras.ru/pool/masternodes/vendor/github.com/jinzhu/gorm/scope.go:1057 +0x2b7
gogs.visteras.ru/pool/masternodes/vendor/github.com/jinzhu/gorm.(*Scope).autoMigrate(0xc04212de00, 0x693ec0)
	C:/box/go/src/gogs.visteras.ru/pool/masternodes/vendor/github.com/jinzhu/gorm/scope.go:1137 +0x3d0
gogs.visteras.ru/pool/masternodes/vendor/github.com/jinzhu/gorm.(*DB).AutoMigrate(0xc042119860, 0xc04206df60, 0x1, 0x1, 0x1)
	C:/box/go/src/gogs.visteras.ru/pool/masternodes/vendor/github.com/jinzhu/gorm/main.go:522 +0x76
main.main()
	C:/box/go/src/gogs.visteras.ru/pool/masternodes/test/trygorm.go:27 +0x102

Process finished with exit code 2
```

**Comment by jinzhu** [comment]
@Vany thank you for your report, fixed.
