### ISSUE TITLE
AutoMigration panic when using composite foreign key

### ISSUE THREAD

**Issue by shavac** [jinzhu/gorm#1780]
**code:**
`
package main

import (
    "github.com/jinzhu/gorm"
    _ "github.com/jinzhu/gorm/dialects/mysql"
    "log"
)

func main() {
    db, err := gorm.Open("mysql", "root:pass@tcp(10.37.129.6:3306)/lynx?parseTime=true")
    if err != nil {
        log.Fatalln("METASTORE:", err)
    }
    db.SingularTable(true)
    db.AutoMigrate(&Db{}, &Table{})
}

type Db struct {
    Uid        int32       `gorm:"AUTO_INCREMENT:false;primary_key"`
    DbName     string      `gorm:"not null"`
    Ckpt       int64       `gorm:"not null;default 0"`
    Stage      int32
    SyncPolicy bool
    Tables []Table `gorm:"foreignkey:Uid,TabId;preload"`
}

type Table struct {
    Uid     int32 `gorm:"AUTO_INCREMENT:false;not null"`
    TabId   int32 `gorm:"AUTO_INCREMENT:false;not null"`
    TabName string
}
`

**error**:

panic: runtime error: index out of range

goroutine 1 [running]:
github.com/jinzhu/gorm.(*Scope).GetModelStruct.func1(0xc00019c080, 0xc0001a6000, 0xc000010030, 0xc0001a04e0)
	/Users/knightmare/Prog/go/src/github.com/jinzhu/gorm/model_struct.go:397 +0x2453
github.com/jinzhu/gorm.(*Scope).GetModelStruct(0xc00019c080, 0xc0001a6000)
	/Users/knightmare/Prog/go/src/github.com/jinzhu/gorm/model_struct.go:606 +0x13b0
github.com/jinzhu/gorm.(*Scope).TableName(0xc00019c080, 0x1132752, 0x12e9920)
	/Users/knightmare/Prog/go/src/github.com/jinzhu/gorm/scope.go:327 +0xfc
github.com/jinzhu/gorm.(*Scope).autoMigrate(0xc00019c080, 0x12879e0)
	/Users/knightmare/Prog/go/src/github.com/jinzhu/gorm/scope.go:1232 +0x40
github.com/jinzhu/gorm.(*DB).AutoMigrate(0xc000194000, 0xc000065f58, 0x2, 0x2, 0x1)
	/Users/knightmare/Prog/go/src/github.com/jinzhu/gorm/main.go:582 +0x6f
main.main()
	/Users/knightmare/tmp/am.go:16 +0x214
exit status 2

**Comment by rcastill** [comment]
Hi @shavac, same problem here, did you solve it?

**Comment by rcastill** [comment]
@shavac, solution is to specify `association_foreignkey`, that solves the problem.

But there's still: #450

**Comment by penguinpowernz** [comment]
Seems that we can track this issue in #450, closing for now.
