### ISSUE TITLE
callback panic!

### ISSUE THREAD

**Issue by qianguozheng** [jinzhu/gorm#2027]
panic: reflect: call of reflect.Value.Interface on zero Value

goroutine 247 [running]:
reflect.valueInterface(0x0, 0x0, 0x0, 0xc420099101, 0xc4203f0ae0, 0xc420099168)
	/usr/local/go/src/reflect/value.go:953 +0x1a3
reflect.Value.Interface(0x0, 0x0, 0x0, 0x0, 0x1)
	/usr/local/go/src/reflect/value.go:948 +0x44
github.com/jinzhu/gorm.createCallback(0xc420151b00)
	/home/weeds/magicwifi/golang/src/github.com/jinzhu/gorm/callback_create.go:68 +0x2d4
github.com/jinzhu/gorm.(*Scope).callCallbacks(0xc420151b00, 0xc420151d80, 0x9, 0x10, 0xc4207eb5f0)
	/home/weeds/magicwifi/golang/src/github.com/jinzhu/gorm/scope.go:857 +0x55
github.com/jinzhu/gorm.(*DB).Create(0xc4207eb5f0, 0x7076e0, 0xc42000c3a0, 0xb)
	/home/weeds/magicwifi/golang/src/github.com/jinzhu/gorm/main.go:434 +0x74
github.com/qianguozheng/goadmin/model.AddSsid(0xc4200ac140, 0x1, 0x4)
	/home/weeds/magicwifi/golang/src/github.com/qianguozheng/goadmin/model/device.go:391 +0x139
_/home/weeds/magicwifi/golang/src/github.com/qianguozheng/tcpserver/control.ParseConfigReadMsg(0xc4200e2008, 0x3dd, 0x3f8, 0xc420014220, 0xc)
	/home/weeds/magicwifi/golang/src/github.com/qianguozheng/tcpserver/control/configread.go:73 +0xae9
_/home/weeds/magicwifi/golang/src/github.com/qianguozheng/tcpserver/server.handleMsg(0xc4200e2008, 0x3dd, 0x3f8, 0x7adf60, 0xc4200aa000, 0xc4201723c0, 0x20002, 0xc42047efa4)
	/home/weeds/magicwifi/golang/src/github.com/qianguozheng/tcpserver/server/msghandler.go:168 +0x32f
_/home/weeds/magicwifi/golang/src/github.com/qianguozheng/tcpserver/server.reader(0xc4201240c0, 0x7adf60, 0xc4200aa000)
	/home/weeds/magicwifi/golang/src/github.com/qianguozheng/tcpserver/server/connectionhandler.go:60 +0xb2
created by _/home/weeds/magicwifi/golang/src/github.com/qianguozheng/tcpserver/server.connectionHandler
	/home/weeds/magicwifi/golang/src/github.com/qianguozheng/tcpserver/server/connectionhandler.go:39 +0x32f
exit status 2

**Comment by qianguozheng** [comment]
DB.Create(&ssid)
