### ISSUE TITLE
ScanRows crashes application when context is cancelled

### ISSUE THREAD

**Issue by pjebs** [jinzhu/gorm#2043]
Your issue may already be reported! Please search on the [issue track](https://github.com/jinzhu/gorm/issues) before creating one.

### What version of Go are you using (`go version`)?

Go 1.10

### Which database and its version are you using?
mysql 5.6

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**

When the incoming context is cancelled, but the cancellation occurs after the `rows.Next()` check in the for loop, then `ScanRows()` crashes application with this error:

The error: `sql: Rows are closed` are caused from the context cancellation. It is not caused from the `defer( )`.

The application crashes with:
```
panic: runtime error: invalid memory address or nil pointer dereference


[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x14bf58a]

goroutine 14 [running]:
github.com/Z/Y/vendor/github.com/jinzhu/gorm.(*DB).print(0xc420320120, 0xc4200fb5a0, 0x2, 0x2)
	/Users/X/GOPATH/src/github.com/Z/Y/vendor/github.com/jinzhu/gorm/main.go:755 +0x2a
created by github.com/Z/Y/vendor/github.com/jinzhu/gorm.(*DB).AddError
	/Users/X/GOPATH/src/github.com/Z/Y/vendor/github.com/jinzhu/gorm/main.go:697 +0x371

```

```
func() X (ctx context.Context) error {

age := 27
rows, err := db.QueryContext(ctx. "SELECT name FROM users WHERE age=?", age)
if err != nil {
        log.Fatal(err)
}
defer func() {
		fmt.Println("will close rows")
		rows.Close()
}()

fakeGormDB := &gorm.DB{} // For example purposes


for rows.Next() {
        err := fakeGormDB.ScanRows(rows, &rawShift) // rawShift is a struct
		if err != nil {
			fmt.Println("error:", err) // sql: Rows are closed
			return err
		}
}
if err := rows.Err(); err != nil {
        log.Fatal(err)
}

}
```

**Comment by pjebs** [comment]
It does not occur when I change from to `if err := rows.Scan( )` from gorm's `ScanRows( )`

**Comment by pjebs** [comment]
My mistake: 
`fakeGormDB := (&gorm.DB{}).LogMode(false)` fixed issue.
