### ISSUE TITLE
panic: invalid sql type  (slice) for mysql

### ISSUE THREAD

**Issue by zwl1619** [jinzhu/gorm#2210]
```
type ProductModel struct {
	BaseModel
	Name  string   `json:"name"  gorm:"not null" binding:"required" validate:"min=2,max=32"`
	Price uint64   `json:"price" gorm:"not null" binding:"required"`
	Pics  []string `json:"pics"  gorm:"default:'[]'"`
}
```
编译出错：
```
[root@vagrant-dev web]# go run main.go
panic: invalid sql type  (slice) for mysql

goroutine 1 [running]:
github.com/jinzhu/gorm.(*mysql).DataTypeOf(0xc00000c440, 0xc00031e690, 0x9, 0x9a9258)
    /var/www/go_work/src/github.com/jinzhu/gorm/dialect_mysql.go:121 +0xd03
github.com/jinzhu/gorm.(*Scope).createTable(0xc0002fe500, 0x9aab38)
    /var/www/go_work/src/github.com/jinzhu/gorm/scope.go:1156 +0x288
github.com/jinzhu/gorm.(*Scope).autoMigrate(0xc0002fe500, 0x93da60)
    /var/www/go_work/src/github.com/jinzhu/gorm/scope.go:1252 +0x3cf
github.com/jinzhu/gorm.(*DB).AutoMigrate(0xc00028ab00, 0xc0001c5f58, 0x1, 0x1, 0xc0003020b0)
    /var/www/go_work/src/github.com/jinzhu/gorm/main.go:596 +0x88
main.main()
    /var/www/go_work/src/apiserver/cmd/web/main.go:27 +0x172
exit status 2
```
好像是Pics字段的问题，改为string可以编译通过，但我想存json，怎么办呢？mysql版本是8.0

**Comment by woniesong92** [comment]
+1

**Comment by StefanBurscher** [comment]
+1

**Comment by StefanBurscher** [comment]
Because database driver don't know how to get the value from []string and save it into database, so you have to implement a Scanner, Driver. please refer: golang.org/pkg/database/sql/#NullString

If you don't want to save it into database, sure, you should ignore it.
