### ISSUE TITLE
[question] How to use txdb with Gorm?

### ISSUE THREAD

**Issue by shackra** [jinzhu/gorm#2595]
I'm trying to use [txdb ](https://github.com/DATA-DOG/go-txdb) for migrating my database inside an isolated transaction. But every time I run my code an error is returned and some warnings are yell by Gorm:

```
testing_1    | === RUN   TestAuthUser
testing_1    | `psql_txdb` is not officially supported, running under compatibility mode.
testing_1    | --- FAIL: TestAuthUser (0.01s)
testing_1    |
testing_1    | (/go/pkg/mod/gopkg.in/gormigrate.v1@v1.4.0/gormigrate.go:346)
testing_1    | [2019-08-06 01:01:28]  pq: current transaction is aborted, commands ignored until end of transaction block
testing_1    | panic: Failed when trying to run migrations: pq: current transaction is aborted, commands ignored until end of transaction block [recovered]
testing_1    |   panic: Failed when trying to run migrations: pq: current transaction is aborted, commands ignored until end of transaction block
testing_1    |
testing_1    | goroutine 51 [running]:
testing_1    | testing.tRunner.func1(0xc0005c4000)
testing_1    |   /usr/local/go/src/testing/testing.go:830 +0x392
testing_1    | panic(0x9d20a0, 0xc000424810)
testing_1    |   /usr/local/go/src/runtime/panic.go:522 +0x1b5
testing_1    | gitlab.com/kuecr/fero/backend.setupWithGroupUser(0xab5bb7, 0xb, 0xc000001980, 0xc0001b1fc0)
testing_1    |   /app/testing.go:46 +0x734
testing_1    | gitlab.com/kuecr/fero/backend.TestAuthUser(0xc0005c4000)
testing_1    |   /app/handle_test.go:12 +0x48
testing_1    | testing.tRunner(0xc0005c4000, 0xb23660)
testing_1    |   /usr/local/go/src/testing/testing.go:865 +0xc0
testing_1    | created by testing.(*T).Run
testing_1    |   /usr/local/go/src/testing/testing.go:916 +0x35a
testing_1    | exit status 2
testing_1    | FAIL      gitlab.com/kuecr/fero/backend   0.141s
testing_1    | make: *** [test] Error 1
testing_1    | Makefile:13: recipe for target 'test' failed
backend_testing_1 exited with code 2
```

This is how setup the database connection:

```
func getDatabaseTx(t string) (*gorm.DB, error) {
	// setup the database
	url := os.Getenv("DATABASE_URL")
	txdb.Register("psql_txdb", "postgres", url)
	db, err := gorm.Open("psql_txdb", t)
	return db, err
}
```

and this is how I use it:

```
db, err := getDatabaseTx("isolated_connection_txdb")
```

I'm following these [notes about sqlmock and Gorm](https://blog.valletta.io/blog/2018-07-05-stub-database-connection-with-gorm/), it should work the same with txdb, but is not the case here.

**Comment by shackra** [comment]
Posted this on Stackoverflow: https://stackoverflow.com/questions/57470228/cant-use-txdb-with-gormigrate
