### ISSUE TITLE
Mysql - Cannot connect to a database with a "-" in its name

### ISSUE THREAD

**Issue by FWangZil** [jinzhu/gorm#2715]
Your issue may already be reported! Please search on the [issue track](https://github.com/jinzhu/gorm/issues) before creating one.

### What version of Go are you using (`go version`)?
go version go1.13 linux/amd64

### Which database and its version are you using?
mysql 5.7

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**

Need to runnable with [GORM's docker compose config](https://github.com/jinzhu/gorm/blob/master/docker-compose.yml) or please provides your config.

```go
func Init() {
	var err error

	dbConfig := conf.GetDatabase()
	DB, err = gorm.Open(dbConfig.Dialect, dbConfig.Dsn)
	if err != nil {
		panic(errkit.Wrapf(err, "failed to connect finance database, database config is %v", dbConfig))
	}
	if dbConfig.Debug {
		DB = DB.Debug()
	}

	DB.AutoMigrate(
		&pkg.test{},
	)
	log.Print("All table AutoMigrate finish.")
}

// Database 数据库配置
type Database struct {
	Dialect string
	Dsn     string
	Debug   bool
}

// GetDatabase 获取数据库配置
func GetDatabase() *Database {
	return &Database{
		Dialect: viper.GetString("database.dialect"),
		Dsn:     viper.GetString("database.dsn"),
		Debug:   viper.GetBool("database.debug"),
	}
}
```

**log**

``` log
Using config file: /var/config/config.yaml
panic: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-kit WHERE Tables_in_pro-kit= ?' at line 1

goroutine 1 [running]:
github.com/jinzhu/gorm.mysql.HasTable(0xc72680, 0xc00032c0c0, 0xc000482100, 0xc000482100, 0xd, 0xf)
	/go/src/github.com/jinzhu/gorm/dialect_mysql.go:172 +0x3bb
github.com/jinzhu/gorm.(*Scope).autoMigrate(0xc0001d5e80, 0xa6d720)
	/go/src/github.com/jinzhu/gorm/scope.go:1262 +0xb3
github.com/jinzhu/gorm.(*DB).AutoMigrate(0xc0002f45b0, 0xc0004a5e58, 0x9, 0x9, 0x1)
	/go/src/github.com/jinzhu/gorm/main.go:657 +0x88
code.aliyun.com/pro/kit/internal/sql.Init()
```

**Comment by FWangZil** [comment]
I found a solution and submitted a new pull request

**Comment by FWangZil** [comment]
I found the problem and submitted a new pull request,But my submission doesn't seem to pass the coverage check.
