### ISSUE TITLE
fatal error: concurrent map iteration and map write

### ISSUE THREAD

**Issue by wins1978** [jinzhu/gorm#2885]
time="2020-02-14T11:16:20.044238269+08:00" level=info msg=" SELECT * FROM wxgv_pgc_graphic_work_order  WHERE allocation_status = 'PENDING' ;" affected=" \n\x1b[36;31m[0 rows affected or returned ]\x1b[0m " catalog=sql duration=" \x1b[36;1m[6.99ms]\x1b[0m " execute_time="\n\x1b[33m[2020-02-14 11:16:20]\x1b[0m" hostname=TENCENT64.site
fatal error: concurrent map iteration and map write

goroutine 5893 [running]:
runtime.throw(0xd751c9, 0x26)
	/usr/local/go/src/runtime/panic.go:617 +0x72 fp=0xc000238600 sp=0xc0002385d0 pc=0x42bf12
runtime.mapiternext(0xc000238748)
	/usr/local/go/src/runtime/map.go:860 +0x597 fp=0xc000238688 sp=0xc000238600 pc=0x40eab7
github.com/sirupsen/logrus.(*Entry).WithFields(0xc0002f6620, 0xc000238800, 0xd5b7cb)
	/data/src/vendor/github.com/sirupsen/logrus/entry.go:117 +0xef fp=0xc0002387b8 sp=0xc000238688 pc=0x56ba5f
git.code.oa.com/fip-team/fiorm.(*GoLogWriter).Println(0x14b4988, 0xc00054f780, 0x5, 0x8)
	/data/src/vendor/git.code.oa.com/fip-team/fiorm/log.go:38 +0x1e6 fp=0xc000238950 sp=0xc0002387b8 pc=0xb34706
github.com/jinzhu/gorm.Logger.Print(0xe8d4a0, 0x14b4988, 0xc000135740, 0x6, 0x6)
	/data/src/vendor/github.com/jinzhu/gorm/logger.go:127 +0x78 fp=0xc000238990 sp=0xc000238950 pc=0xae0258
github.com/jinzhu/gorm.(*Logger).Print(0xc000443230, 0xc000135740, 0x6, 0x6)
	<autogenerated>:1 +0x63 fp=0xc0002389c8 sp=0xc000238990 pc=0xb0ed53
github.com/jinzhu/gorm.(*DB).print(...)
	/data/src/vendor/github.com/jinzhu/gorm/main.go:841
github.com/jinzhu/gorm.(*DB).slog(0xc00019d040, 0xc0001ef0e0, 0x8d, 0xbf89a2210295e961, 0x8b907ed8c1, 0x1496b00, 0xc0003e82d0, 0x1, 0x1)
	/data/src/vendor/github.com/jinzhu/gorm/main.go:852 +0x248 fp=0xc000238a50 sp=0xc0002389c8 pc=0xae86e8
github.com/jinzhu/gorm.(*Scope).trace(0xc00054f600, 0xbf89a2210295e961, 0x8b907ed8c1, 0x1496b00)
	/data/src/vendor/github.com/jinzhu/gorm/scope.go:1045 +0x89 fp=0xc000238aa8 sp=0xc000238a50 pc=0xaf79a9
github.com/jinzhu/gorm.(*Scope).Exec(0xc00054f600, 0xc00054f600)
	/data/src/vendor/github.com/jinzhu/gorm/scope.go:370 +0xad fp=0xc000238b30 sp=0xc000238aa8 pc=0xaee39d
github.com/jinzhu/gorm.(*DB).Exec(0xc00012e410, 0xc0001eef30, 0x8d, 0xc0003e82a0, 0x1, 0x1, 0xc000444de0)
	/data/src/vendor/github.com/jinzhu/gorm/main.go:499 +0x2bd fp=0xc000238cf8 sp=0xc000238b30 pc=0xae58ad
git.code.oa.com/fip-team/fiorm.(*FiDB).Exec(0xc000759020, 0xc0001eef30, 0x8d, 0xc0003e82a0, 0x1, 0x1, 0x8d, 0x0)
	/data/src/vendor/git.code.oa.com/fip-team/fiorm/main.go:625 +0x7b fp=0xc000238d58 sp=0xc000238cf8 pc=0xb376eb
git.code.oa.com/ev_platform/ev_workorderpool/service.getAllNoFilterOrders(0xc00071c150, 0x26, 0xc0007a8580, 0x2, 0x2, 0xc00071c0f0, 0x24, 0x0, 0x0, 0x0, ...)
	/data/src/service/pretreatment.go:126 +0x420 fp=0xc0002393c0 sp=0xc000238d58 pc=0xb896f0
git.code.oa.com/ev_platform/ev_workorderpool/service.OrderFilter(0x4, 0x2, 0xc000247a00, 0x1, 0x4, 0xc000035e70, 0x7, 0x3ff0000000000000, 0x0, 0x0, ...)
	/data/src/service/pretreatment.go:103 +0x340 fp=0xc000239888 sp=0xc0002393c0 pc=0xb88fe0
git.code.oa.com/ev_platform/ev_workorderpool/api.OrderFilter(0xc0002d5d90)
	/data/src/api/pretreatment.go:60 +0x10e fp=0xc000239978 sp=0xc000239888 pc=0xb9ecae
github.com/gin-gonic/gin.(*Context).Next(0xc0002d5d90)
	/data/src/vendor/github.com/gin-gonic/gin/context.go:124 +0x3a fp=0xc000239990 sp=0xc000239978 pc=0xa71f9a
git.code.oa.com/fip-team/fikits/mw/exception.Handle(0xc0002d5d90)
	/data/src/vendor/git.code.oa.com/fip-team/fikits/mw/exception/handler.go:64 +0x51 fp=0xc0002399b8 sp=0xc000239990 pc=0xba64d1
github.com/gin-gonic/gin.(*Context).Next(0xc0002d5d90)
	/data/src/vendor/github.com/gin-gonic/gin/context.go:124 +0x3a fp=0xc0002399d0 sp=0xc0002399b8 pc=0xa71f9a
git.code.oa.com/fip-team/fikits/mw/logger.UseLogger.func1(0xc0002d5d90)
	/data/src/vendor/git.code.oa.com/fip-team/fikits/mw/logger/logger.go:120 +0x2e2 fp=0xc000239b70 sp=0xc0002399d0 pc=0xa86c12
github.com/gin-gonic/gin.(*Context).Next(0xc0002d5d90)
	/data/src/vendor/github.com/gin-gonic/gin/context.go:124 +0x3a fp=0xc000239b88 sp=0xc000239b70 pc=0xa71f9a
github.com/gin-gonic/gin.RecoveryWithWriter.func1(0xc0002d5d90)
	/data/src/vendor/github.com/gin-gonic/gin/recovery.go:83 +0x5a fp=0xc000239bb8 sp=0xc000239b88 pc=0xa83c7a
github.com/gin-gonic/gin.(*Context).Next(0xc0002d5d90)
	/data/src/vendor/github.com/gin-gonic/gin/context.go:124 +0x3a fp=0xc000239bd0 sp=0xc000239bb8 pc=0xa71f9a
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc000441320, 0xc0002d5d90)
	/data/src/vendor/github.com/gin-gonic/gin/gin.go:389 +0x5b2 fp=0xc000239cb8 sp=0xc000239bd0 pc=0xa7b482
github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc000441320, 0xe9fa40, 0xc0001722a0, 0xc000247900)
	/data/src/vendor/github.com/gin-gonic/gin/gin.go:351 +0x134 fp=0xc000239cf0 sp=0xc000239cb8 pc=0xa7acb4
net/http.serverHandler.ServeHTTP(0xc00034b2b0, 0xe9fa40, 0xc0001722a0, 0xc000247900)
	/usr/local/go/src/net/http/server.go:2774 +0xa8 fp=0xc000239d20 sp=0xc000239cf0 pc=0x6f5b28
net/http.(*conn).serve(0xc0003e0820, 0xea2a80, 0xc0001d81c0)
	/usr/local/go/src/net/http/server.go:1878 +0x851 fp=0xc000239fc8 sp=0xc000239d20 pc=0x6f1711
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc000239fd0 sp=0xc000239fc8 pc=0x4581b1
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2884 +0x2f4

goroutine 1 [IO wait]:
internal/poll.runtime_pollWait(0x7f38a5acfe10, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:182 +0x56
internal/poll.(*pollDesc).wait(0xc00041cd98, 0x72, 0x0, 0x0, 0xd5a4f5)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x9b
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc00041cd80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:384 +0x1ba
net.(*netFD).accept(0xc00041cd80, 0xc00004ef70, 0xc00004ef00, 0x40b759)
	/usr/local/go/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc000346f90, 0xc000460ca0, 0x25c4edaa, 0x40fdc4e416f3a20e)
	/usr/local/go/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).AcceptTCP(0xc000346f90, 0xc000460cc8, 0x4b3e16, 0x5e461104)
	/usr/local/go/src/net/tcpsock.go:247 +0x48
net/http.tcpKeepAliveListener.Accept(0xc000346f90, 0xc000460d18, 0x18, 0xc000000180, 0x6f5fd4)
	/usr/local/go/src/net/http/server.go:3264 +0x2f
net/http.(*Server).Serve(0xc00034b2b0, 0xea0180, 0xc000346f90, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2859 +0x22d
net/http.(*Server).ListenAndServe(0xc00034b2b0, 0xc00034b2b0, 0xc000169e78)
	/usr/local/go/src/net/http/server.go:2797 +0xe4
net/http.ListenAndServe(...)
	/usr/local/go/src/net/http/server.go:3037
github.com/gin-gonic/gin.(*Engine).Run(0xc000441320, 0xc000169f00, 0x1, 0x1, 0x0, 0x0)
	/data/src/vendor/github.com/gin-gonic/gin/gin.go:294 +0x140
main.startServer()
	/data/src/main.go:69 +0x312
main.main()
	/data/src/main.go:33 +0x12a

goroutine 22 [select]:
net/http.(*persistConn).roundTrip(0xc0001b85a0, 0xc0004d2810, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:2194 +0x75c
net/http.(*Transport).roundTrip(0x148a0c0, 0xc000247d00, 0xc0004d27e0, 0xc0001e6ef0, 0xc0001e6ed4)
	/usr/local/go/src/net/http/transport.go:481 +0xa1b
net/http.(*Transport).RoundTrip(0x148a0c0, 0xc000247d00, 0x148a0c0, 0xbf89a22b7698ea6b, 0x95504c33e6)
	/usr/local/go/src/net/http/roundtrip.go:17 +0x35
net/http.send(0xc000247c00, 0xe8e6c0, 0x148a0c0, 0xbf89a22b7698ea6b, 0x95504c33e6, 0x1496b00, 0xc00000e8f0, 0xbf89a22b7698ea6b, 0x1, 0x0)
	/usr/local/go/src/net/http/client.go:250 +0x461
net/http.(*Client).send(0xc0001a84e0, 0xc000247c00, 0xbf89a22b7698ea6b, 0x95504c33e6, 0x1496b00, 0xc00000e8f0, 0x0, 0x1, 0x0)
	/usr/local/go/src/net/http/client.go:174 +0xfb
net/http.(*Client).do(0xc0001a84e0, 0xc000247c00, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:641 +0x279
net/http.(*Client).Do(0xc0001a84e0, 0xc000247c00, 0xc7, 0x400, 0xc0002cc8f0)
	/usr/local/go/src/net/http/client.go:509 +0x35
github.com/shima-park/agollo.parseResponseBody(0xe8e660, 0xc0001a84e0, 0xc000247c00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/data/src/vendor/github.com/shima-park/agollo/apollo_client.go:235 +0x64
github.com/shima-park/agollo.(*apolloClient).Notifications(0xc0001a84b0, 0xc0000c2b10, 0x2e, 0xc000037460, 0x11, 0xd5a6fb, 0x7, 0xc00041b060, 0x1, 0x1, ...)
	/data/src/vendor/github.com/shima-park/agollo/apollo_client.go:124 +0x35e
github.com/shima-park/agollo.(*agollo).longPoll(0xc000001080)
	/data/src/vendor/github.com/shima-park/agollo/agollo.go:373 +0xb0
github.com/shima-park/agollo.(*agollo).Start.func1.1(0xc000001080)
	/data/src/vendor/github.com/shima-park/agollo/agollo.go:425 +0x89
created by github.com/shima-park/agollo.(*agollo).Start.func1
	/data/src/vendor/github.com/shima-park/agollo/agollo.go:418 +0x3e

**Comment by wins1978** [comment]
check is not gorm issues,but logrus log?
