### ISSUE TITLE
Using pointer in structs panics

### ISSUE THREAD

**Issue by joiggama** [jinzhu/gorm#374]
I started having panics using pointers as struct fields as the following:
```go
package main

import (
  "github.com/jinzhu/gorm"
  _ "github.com/lib/pq"
)

type Foo struct {
  Id     int64
  BarId *int64
}

func main() {
  db, err := gorm.Open("postgres", "postgres://localhost/gorm?sslmode=disable")

  if err != nil {
    panic(err)
  }

  db.LogMode(true)

  var foo Foo
  err = db.First(&foo).Error

  if err != nil {
    panic(err)
  }
}
```
The backtrace:
```
$ go run main.go
panic: invalid sql type  (ptr) for postgres

goroutine 1 [running]:
github.com/jinzhu/gorm.(*postgres).SqlTag(0x46b788, 0x223b60, 0xc20802c038, 0xd6, 0xff, 0x0, 0x0)
        /Users/joiggama/.go/src/github.com/jinzhu/gorm/postgres.go:56 +0x388
github.com/jinzhu/gorm.(*Scope).generateSqlTag(0xc20803e900, 0xc20809c0e0)
        /Users/joiggama/.go/src/github.com/jinzhu/gorm/model_struct.go:101 +0x83f
github.com/jinzhu/gorm.(*Scope).GetModelStruct(0xc20803e900, 0x0, 0x0, 0x0, 0x2386c0)
        /Users/joiggama/.go/src/github.com/jinzhu/gorm/model_struct.go:323 +0x1b97
github.com/jinzhu/gorm.(*Scope).PrimaryKeyField(0xc20803e900, 0x18)
        /Users/joiggama/.go/src/github.com/jinzhu/gorm/scope.go:101 +0x44
github.com/jinzhu/gorm.(*Scope).PrimaryKey(0xc20803e900, 0x0, 0x0)
        /Users/joiggama/.go/src/github.com/jinzhu/gorm/scope.go:109 +0x3a
github.com/jinzhu/gorm.Query(0xc20803e900)
        /Users/joiggama/.go/src/github.com/jinzhu/gorm/callback_query.go:24 +0x1fc
github.com/jinzhu/gorm.(*Scope).callCallbacks(0xc20803e900, 0xc20801fea0, 0x3, 0x4, 0xc20803e900)
        /Users/joiggama/.go/src/github.com/jinzhu/gorm/scope_private.go:304 +0x6b
github.com/jinzhu/gorm.(*DB).First(0xc20805caa0, 0x223f20, 0xc20800b9c0, 0x0, 0x0, 0x0, 0x0)
        /Users/joiggama/.go/src/github.com/jinzhu/gorm/main.go:186 +0x284
main.main()
        /Users/joiggama/.go/src/github.com/joiggama/gorm-fix/main.go:23 +0x265

goroutine 5 [runnable]:
database/sql.(*DB).connectionOpener(0xc20805cbe0)
        /usr/local/Cellar/go/1.4.1/libexec/src/database/sql/sql.go:588
created by database/sql.Open
        /usr/local/Cellar/go/1.4.1/libexec/src/database/sql/sql.go:452 +0x31c
exit status 2
```

I've tried to track it, and I started seeing this problem after 139b9a37e7b6d549212863bfa4fcfde4243d397e.

I couldn't come out with a fix for this, but tried playing around here https://github.com/jinzhu/gorm/blob/master/postgres.go#L28-L57.

Is the usage of struct field pointers discouraged?

**Comment by jinzhu** [comment]
Thank you for your report, just pushed a commit to fix the issue.

**Comment by joiggama** [comment]
Thanks to you :)
