### ISSUE TITLE
Using slices as struct fields causes panics.

### ISSUE THREAD

**Issue by joiggama** [jinzhu/gorm#375]
Hey, I've discovered that recently using slices in struct fields causes panics, It seems that might be a bug, anyway a workaround is ignore it with a sql tag.

```go
package main

import (
  "github.com/jinzhu/gorm"
  _ "github.com/lib/pq"
)

type Foo struct {
    Id     int64
    BarIds []int64
}

func main() {
  db, err := gorm.Open("postgres", "postgres://localhost/gorm?sslmode=disable")

  if err != nil {
    panic(err)
  }

  db.LogMode(true)

  var foo Foo
  err = db.First(&foo).Error

  if err != nil {
    panic(err)
  }
}
```

The backtrace:
```
 $ go run main.go
panic: invalid sql type  (slice) for postgres

goroutine 1 [running]:
github.com/jinzhu/gorm.(*postgres).SqlTag(0x46b7c8, 0x22af80, 0xc2080940a0, 0xd7, 0xff, 0x0, 0x0)
        /Users/joiggama/.go/src/github.com/jinzhu/gorm/postgres.go:56 +0x388
github.com/jinzhu/gorm.(*Scope).generateSqlTag(0xc20803e900, 0xc2080920e0)
        /Users/joiggama/.go/src/github.com/jinzhu/gorm/model_struct.go:105 +0x8a4
github.com/jinzhu/gorm.(*Scope).GetModelStruct(0xc20803e900, 0x0, 0x0, 0x0, 0x237620)
        /Users/joiggama/.go/src/github.com/jinzhu/gorm/model_struct.go:327 +0x1b97
github.com/jinzhu/gorm.(*Scope).PrimaryKeyField(0xc20803e900, 0x18)
        /Users/joiggama/.go/src/github.com/jinzhu/gorm/scope.go:102 +0x44
github.com/jinzhu/gorm.(*Scope).PrimaryKey(0xc20803e900, 0x0, 0x0)
        /Users/joiggama/.go/src/github.com/jinzhu/gorm/scope.go:110 +0x3a
github.com/jinzhu/gorm.Query(0xc20803e900)
        /Users/joiggama/.go/src/github.com/jinzhu/gorm/callback_query.go:24 +0x1fc
github.com/jinzhu/gorm.(*Scope).callCallbacks(0xc20803e900, 0xc20801fea0, 0x3, 0x4, 0xc20803e900)
        /Users/joiggama/.go/src/github.com/jinzhu/gorm/scope_private.go:304 +0x6b
github.com/jinzhu/gorm.(*DB).First(0xc208030a00, 0x28ff80, 0xc20801fee0, 0x0, 0x0, 0x0, 0x0)
        /Users/joiggama/.go/src/github.com/jinzhu/gorm/main.go:186 +0x1b1
main.main()
        /Users/joiggama/.go/src/github.com/joiggama/gorm-fix/main.go:29 +0x2ba

goroutine 2 [runnable]:
runtime.forcegchelper()
        /usr/local/Cellar/go/1.4.2/libexec/src/runtime/proc.go:90
runtime.goexit()
        /usr/local/Cellar/go/1.4.2/libexec/src/runtime/asm_amd64.s:2232 +0x1

goroutine 3 [runnable]:
runtime.bgsweep()
        /usr/local/Cellar/go/1.4.2/libexec/src/runtime/mgc0.go:82
runtime.goexit()
        /usr/local/Cellar/go/1.4.2/libexec/src/runtime/asm_amd64.s:2232 +0x1

goroutine 4 [runnable]:
runtime.runfinq()
        /usr/local/Cellar/go/1.4.2/libexec/src/runtime/malloc.go:712
runtime.goexit()
        /usr/local/Cellar/go/1.4.2/libexec/src/runtime/asm_amd64.s:2232 +0x1

goroutine 5 [runnable]:
database/sql.(*DB).connectionOpener(0xc208030b40)
        /usr/local/Cellar/go/1.4.2/libexec/src/database/sql/sql.go:588
created by database/sql.Open
        /usr/local/Cellar/go/1.4.2/libexec/src/database/sql/sql.go:452 +0x31c
exit status 2
```

**Comment by jinzhu** [comment]
Hi @joiggama 

Because database driver don't know how to get the value from `[]int64` and save it into database, so you have to implement a Scanner, Driver. please refer: golang.org/pkg/database/sql/#NullString

**Comment by joiggama** [comment]
I understand. The reason I reported this it was because this is a recent behaviour, previously this didn't cause panics. Anyway, I'm ok with ignoring via sql tags. Thank you.
