### ISSUE TITLE
SQLite file locks

### ISSUE THREAD

**Issue by Alexeyco** [jinzhu/gorm#549]
I have 2 related models

```
type Link struct {
	ID           uint   `sql:"primary_key;auto_increment"`
	URL          string `sql:"type:text;unique"`
	ContentType  string
	LastModified time.Time
	Logs         []Log `db:"-"`
}

type Log struct {
	ID     uint `sql:"primary_key;auto_increment"`
	Date   time.Time
	LinkID uint
	Status int
	Link   Link
}
```

When I try to this:
```
link := Link{
	URL:         remoteUrl,
	ContentType: contentType,
	link.LastModified = lastModified
}

db.Create(&link)
db.Model(&link).Association("Logs").Append(Log{
	Date:   time.Now(),
	Status: response.StatusCode,
})
```

I giving this error:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x1 addr=0x0 pc=0x4af57a]

goroutine 1 [running]:
github.com/jinzhu/gorm.(*Association).Append(0xc0820af580, 0xc08206fb50, 0x1, 0x
1, 0xc0820ad380)
        C:/***/gorm/association.go:36 +0x3fa

main.(*Parser).Load(0xc08205f4a0, 0x843130, 0x17, 0x0, 0x0, 0x0, 0x0)
        c:/***/main.go:84 +0x817

main.main()
        c:/***/main.go:145 +0x45
b

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        c:/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 5 [chan receive]:
database/sql.(*DB).connectionOpener(0xc082050500)
        c:/go/src/database/sql/sql.go:589 +0x53
created by database/sql.Open
        c:/go/src/database/sql/sql.go:452 +0x323

goroutine 12 [select]:
net/http.(*persistConn).writeLoop(0xc0820ba000)
        c:/go/src/net/http/transport.go:945 +0x424
created by net/http.(*Transport).dialConn
        c:/go/src/net/http/transport.go:661 +0xcc3

goroutine 11 [select]:
net/http.(*persistConn).readLoop(0xc0820ba000)
        c:/go/src/net/http/transport.go:928 +0x9d5
created by net/http.(*Transport).dialConn
        c:/go/src/net/http/transport.go:660 +0xca6
exit status 2
```

**Comment by Alexeyco** [comment]
But if `link` is already in the database, and we get it through SELECT, recording new `log` passes without problems.

**Comment by jinzhu** [comment]
```go
package main

import (
	"time"

	_ "github.com/go-sql-driver/mysql"
	"github.com/jinzhu/gorm"
	_ "github.com/mattn/go-sqlite3"
)

type Link struct {
	ID           uint   `sql:"primary_key;auto_increment"`
	URL          string `sql:"unique"`
	ContentType  string
	LastModified time.Time
	Logs         []Log `db:"-"`
}

type Log struct {
	ID     uint `sql:"primary_key;auto_increment"`
	Date   time.Time
	LinkID uint
	Status int
	Link   Link
}

func main() {
	// dbuser, dbpwd := "gorm", "gorm"
	// db, err := gorm.Open(
	// 	"mysql",
	// 	fmt.Sprintf("%s:%s@/gorm?parseTime=True&loc=Local", dbuser, dbpwd),
	// )
	db, err := gorm.Open("sqlite3", "/tmp/gorm.db")
	if err != nil {
		panic(err)
	}
	db.LogMode(true)
	db.AutoMigrate(&Link{}, &Log{})

	link := Link{
		URL:          "remoteUrl",
		ContentType:  "contentType",
		LastModified: time.Now(),
	}

	db.Create(&link)
	db.Model(&link).Association("Logs").Append(Log{
		Date:   time.Now(),
		Status: 200,
	})
}

```

seems haven't got any problem
