### ISSUE TITLE
Association.Append with foreign keys panics

### ISSUE THREAD

**Issue by stroborobo** [jinzhu/gorm#681]
Hi,

since a480621 this panics: http://play.golang.org/p/uFg7mEM47H

`relationship.JoinTableHandler` is nil

Stacktrace:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0xa2049]

goroutine 1 [running]:
github.com/jinzhu/gorm.(*Association).Append.func1(0x32ae60, 0xc82040e260, 0xd9)
        /Users/bo/src/go/src/github.com/Knorkebrot/gorm-test-append/Godeps/_workspace/src/github.com/jinzhu/gorm/association.go:46 +0x319
github.com/jinzhu/gorm.(*Association).Append(0xc8203e9ce0, 0xc82008fe20, 0x1, 0x1, 0x1)
        /Users/bo/src/go/src/github.com/Knorkebrot/gorm-test-append/Godeps/_workspace/src/github.com/jinzhu/gorm/association.go:61 +0x1b5
main.main()
        /Users/bo/src/go/src/github.com/Knorkebrot/gorm-test-append/main.go:45 +0x74b
```

**Comment by jinzhu** [comment]
This should been fixed, haven't got any error when latest gorm.

Thank you for your report.

**Comment by stroborobo** [comment]
Hey jinzhu, works now, thank you!
