### ISSUE TITLE
Getting panic on rollback 

### ISSUE THREAD

**Issue by danbogos** [jinzhu/gorm#747]
Hey,

Thank you for this neat package, it serves us well!

Not sure if you got already this panic handled and you already have some tips for us but when MySQL is not accepting new connections, we will get panic on rollback. Bellow the strace. Thanks in advance for any kind of tip!

```
2015/12/02 11:36:35 http: panic serving 192.168.133.154:39506: runtime error: invalid memory address or nil pointer dereference
goroutine 1485 [running]:
net/http.(*conn).serve.func1(0xc8204ae790, 0x7f7d0857cb30, 0xc820026190)
        /usr/local/go/src/net/http/server.go:1287 +0xb5
database/sql.(*Tx).Rollback(0x0, 0x0, 0x0)
        /usr/local/go/src/database/sql/sql.go:1149 +0x28
github.com/jinzhu/gorm.(*DB).Rollback(0xc8208370e0, 0xdd8580)
        /home/byron/GOPATH/src/github.com/jinzhu/gorm/main.go:360 +0x8d
github.com/cgrates/cgrates/engine.(*SQLStorage).SetCdr(0xc820094000, 0xc821026680, 0x0, 0x0)
        /home/byron/GOPATH/src/github.com/cgrates/cgrates/engine/storage_sql.go:626 +0x746
github.com/cgrates/cgrates/engine.(*CdrServer).processCdr(0xc820492230, 0xc821026680, 0x0, 0x0)
        /home/byron/GOPATH/src/github.com/cgrates/cgrates/engine/cdrs.go:206 +0x3c8
github.com/cgrates/cgrates/engine.fsCdrHandler(0x7f7d08584430, 0xc820095e40, 0xc8214cc000)
        /home/byron/GOPATH/src/github.com/cgrates/cgrates/engine/cdrs.go:63 +0x2ab
net/http.HandlerFunc.ServeHTTP(0x115dd10, 0x7f7d08584430, 0xc820095e40, 0xc8214cc000)
        /usr/local/go/src/net/http/server.go:1422 +0x3a
net/http.(*ServeMux).ServeHTTP(0xc820065050, 0x7f7d08584430, 0xc820095e40, 0xc8214cc000)
        /usr/local/go/src/net/http/server.go:1699 +0x17d
net/http.serverHandler.ServeHTTP(0xc820061200, 0x7f7d08584430, 0xc820095e40, 0xc8214cc000)
        /usr/local/go/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc8204ae790)
        /usr/local/go/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:1910 +0x3f6

(Error 1040: Too many connections) 
[2015-12-02 11:36:35]  

(Error 1040: Too many connections) 
[2015-12-02 11:36:35]  
2015/12/02 11:36:36 http: panic serving 192.168.133.154:39508: runtime error: invalid memory address or nil pointer dereference
goroutine 1510 [running]:
net/http.(*conn).serve.func1(0xc8204ae790, 0x7f7d0857cb30, 0xc820534068)
        /usr/local/go/src/net/http/server.go:1287 +0xb5
database/sql.(*Tx).Rollback(0x0, 0x0, 0x0)
        /usr/local/go/src/database/sql/sql.go:1149 +0x28
github.com/jinzhu/gorm.(*DB).Rollback(0xc821273d60, 0xdd8580)
        /home/byron/GOPATH/src/github.com/jinzhu/gorm/main.go:360 +0x8d
github.com/cgrates/cgrates/engine.(*SQLStorage).SetCdr(0xc820094000, 0xc8210264e0, 0x0, 0x0)
        /home/byron/GOPATH/src/github.com/cgrates/cgrates/engine/storage_sql.go:626 +0x746
github.com/cgrates/cgrates/engine.(*CdrServer).processCdr(0xc820492230, 0xc8210264e0, 0x0, 0x0)
        /home/byron/GOPATH/src/github.com/cgrates/cgrates/engine/cdrs.go:206 +0x3c8
github.com/cgrates/cgrates/engine.fsCdrHandler(0x7f7d08584430, 0xc820095e40, 0xc8214cc000)
        /home/byron/GOPATH/src/github.com/cgrates/cgrates/engine/cdrs.go:63 +0x2ab
net/http.HandlerFunc.ServeHTTP(0x115dd10, 0x7f7d08584430, 0xc820095e40, 0xc8214cc000)
        /usr/local/go/src/net/http/server.go:1422 +0x3a
net/http.(*ServeMux).ServeHTTP(0xc820065050, 0x7f7d08584430, 0xc820095e40, 0xc8214cc000)
        /usr/local/go/src/net/http/server.go:1699 +0x17d
net/http.serverHandler.ServeHTTP(0xc820061200, 0x7f7d08584430, 0xc820095e40, 0xc8214cc000)
        /usr/local/go/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc8204ae790)
        /usr/local/go/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:1910 +0x3f6

(Error 1040: Too many connections) 
[2015-12-02 11:36:36]  

(Error 1040: Too many connections) 
[2015-12-02 11:36:36]  
2015/12/02 11:36:36 http: panic serving 192.168.133.154:39509: runtime error: invalid memory address or nil pointer dereference
goroutine 1519 [running]:
net/http.(*conn).serve.func1(0xc8207c6630, 0x7f7d0857cb30, 0xc82006d998)
        /usr/local/go/src/net/http/server.go:1287 +0xb5
database/sql.(*Tx).Rollback(0x0, 0x0, 0x0)
        /usr/local/go/src/database/sql/sql.go:1149 +0x28
github.com/jinzhu/gorm.(*DB).Rollback(0xc820ddf040, 0xdd8580)
        /home/byron/GOPATH/src/github.com/jinzhu/gorm/main.go:360 +0x8d
github.com/cgrates/cgrates/engine.(*SQLStorage).SetCdr(0xc820094000, 0xc820bab860, 0x0, 0x0)
        /home/byron/GOPATH/src/github.com/cgrates/cgrates/engine/storage_sql.go:626 +0x746
github.com/cgrates/cgrates/engine.(*CdrServer).processCdr(0xc820492230, 0xc820bab860, 0x0, 0x0)
        /home/byron/GOPATH/src/github.com/cgrates/cgrates/engine/cdrs.go:206 +0x3c8
github.com/cgrates/cgrates/engine.fsCdrHandler(0x7f7d08584430, 0xc8207c66e0, 0xc820f6fc00)
        /home/byron/GOPATH/src/github.com/cgrates/cgrates/engine/cdrs.go:63 +0x2ab
net/http.HandlerFunc.ServeHTTP(0x115dd10, 0x7f7d08584430, 0xc8207c66e0, 0xc820f6fc00)
        /usr/local/go/src/net/http/server.go:1422 +0x3a
net/http.(*ServeMux).ServeHTTP(0xc820065050, 0x7f7d08584430, 0xc8207c66e0, 0xc820f6fc00)
        /usr/local/go/src/net/http/server.go:1699 +0x17d
net/http.serverHandler.ServeHTTP(0xc820061200, 0x7f7d08584430, 0xc8207c66e0, 0xc820f6fc00)
        /usr/local/go/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc8207c6630)
        /usr/local/go/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:1910 +0x3f6

(Error 1040: Too many connections) 
[2015-12-02 11:36:36] 
```
DanB

**Comment by jinzhu** [comment]
Hi @danbogos 

Thank you for your report, but I haven't seen this error before, so maybe I can do nothing to help you. ;(

As this is not a gorm related bug, so going to close this for now.

Thank you.

**Comment by danbogos** [comment]
Hi @jinzhu 

Thanks for checking it out. If by any chance you hit the panic in the future, please inform me in this issue.

Thanks again!

DanB

**Comment by kmulvey** [comment]
Hi @jinzhu @danbogos  i think i have hit the same problem. This occurs while testing pulling the plug on mysql

```
[mysql] 2016/11/07 08:35:42 packets.go:405: busy buffer
[mysql] 2016/11/07 08:35:42 packets.go:386: busy buffer
[mysql] 2016/11/07 08:35:42 packets.go:405: busy buffer
[mysql] 2016/11/07 08:35:42 packets.go:386: busy buffer
dial tcp 127.0.0.1:3306: getsockopt: connection refused 
dial tcp 127.0.0.1:3306: getsockopt: connection refused 
dial tcp 127.0.0.1:3306: getsockopt: connection refused 
dial tcp 127.0.0.1:3306: getsockopt: connection refused 

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x6d0c56]

goroutine 6 [running]:
panic(0x928fc0, 0xc42000c110)
        /usr/lib/golang/src/runtime/panic.go:500 +0x1a1
database/sql.(*Tx).Rollback(0x0, 0x7fb58eb07940, 0x0)
        /usr/lib/golang/src/database/sql/sql.go:1264 +0x26
github.com/jinzhu/gorm.(*DB).Rollback(0xc420e70820, 0xc420667840)
        /opt/code/go/src/github.com/jinzhu/gorm/main.go:460 +0x81
github.com/---/janus/user.LoadUsers(0x7fb58eb060a0, 0xc4201bda40)
        /opt/code/go/src/github.com/---/janus/user/user.go:527 +0x33d0
github.com/---/janus/user.SyncWithMaster(0x7fb58eb060a0, 0xc4201bda40)
        /opt/code/go/src/github.com/---/janus/user/user.go:340 +0xfd
created by main.syncWithMaster
        /opt/code/go/src/github.com/---/janus/main.go:194 +0x12f

```

**Comment by hookover** [comment]
> Hi @jinzhu @danbogos i think i have hit the same problem. This occurs while testing pulling the plug on mysql
> 
> ```
> [mysql] 2016/11/07 08:35:42 packets.go:405: busy buffer
> [mysql] 2016/11/07 08:35:42 packets.go:386: busy buffer
> [mysql] 2016/11/07 08:35:42 packets.go:405: busy buffer
> [mysql] 2016/11/07 08:35:42 packets.go:386: busy buffer
> dial tcp 127.0.0.1:3306: getsockopt: connection refused 
> dial tcp 127.0.0.1:3306: getsockopt: connection refused 
> dial tcp 127.0.0.1:3306: getsockopt: connection refused 
> dial tcp 127.0.0.1:3306: getsockopt: connection refused 
> 
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x6d0c56]
> 
> goroutine 6 [running]:
> panic(0x928fc0, 0xc42000c110)
>         /usr/lib/golang/src/runtime/panic.go:500 +0x1a1
> database/sql.(*Tx).Rollback(0x0, 0x7fb58eb07940, 0x0)
>         /usr/lib/golang/src/database/sql/sql.go:1264 +0x26
> github.com/jinzhu/gorm.(*DB).Rollback(0xc420e70820, 0xc420667840)
>         /opt/code/go/src/github.com/jinzhu/gorm/main.go:460 +0x81
> github.com/---/janus/user.LoadUsers(0x7fb58eb060a0, 0xc4201bda40)
>         /opt/code/go/src/github.com/---/janus/user/user.go:527 +0x33d0
> github.com/---/janus/user.SyncWithMaster(0x7fb58eb060a0, 0xc4201bda40)
>         /opt/code/go/src/github.com/---/janus/user/user.go:340 +0xfd
> created by main.syncWithMaster
>         /opt/code/go/src/github.com/---/janus/main.go:194 +0x12f
> ```
excuse me, have you solved the problem?
