### ISSUE TITLE
Preload reflection failure

### ISSUE THREAD

**Issue by arthurprs** [jinzhu/gorm#827]
This test case
```
func TestNestedPreload2(t *testing.T) {
	type (
		Level1 struct {
			ID       uint
			Value    string
			Level2ID uint
		}
		Level2 struct {
			ID       uint
			Level1s  []*Level1
			Level3ID uint
		}
		Level3 struct {
			ID      uint
			Name    string
			Level2s []*Level2
		}
	)
	DB.DropTableIfExists(&Level3{})
	DB.DropTableIfExists(&Level2{})
	DB.DropTableIfExists(&Level1{})
	if err := DB.AutoMigrate(&Level3{}, &Level2{}, &Level1{}).Error; err != nil {
		t.Error(err)
	}

	want := []*Level3 {
		{
			Level2s: []*Level2{
				{
					Level1s: []*Level1{
						&Level1{Value: "value1"},
						&Level1{Value: "value2"},
					},
				},
				{
					Level1s: []*Level1{
						&Level1{Value: "value3"},
					},
				},
			},
		},
	}
	if err := DB.Create(&want[0]).Error; err != nil {
		t.Error(err)
	}

	var got []*Level3
	if err := DB.Preload("Level2s").Preload("Level2s.Level1s").Find(&got).Error; err != nil {
		t.Error(err)
	}

	if !reflect.DeepEqual(got, want) {
		t.Errorf("got %s; want %s", toJSONString(got), toJSONString(want))
	}
}
```

fails with

```
panic: reflect: call of reflect.Value.FieldByName on ptr Value [recovered]
	panic: reflect: call of reflect.Value.FieldByName on ptr Value

goroutine 52 [running]:
testing.tRunner.func1(0xc820011170)
	/home/arthurprs/.gvm/gos/go1.5.1/src/testing/testing.go:450 +0x171
reflect.flag.mustBe(0xd6, 0x19)
	/home/arthurprs/.gvm/gos/go1.5.1/src/reflect/value.go:199 +0xa6
reflect.Value.FieldByName(0x86ef80, 0xc8207c24e0, 0xd6, 0x9a5150, 0x7, 0x0, 0x0, 0x0)
	/home/arthurprs/.gvm/gos/go1.5.1/src/reflect/value.go:788 +0x53
github.com/jinzhu/gorm.(*Scope).handleHasManyPreload(0xc82079ef00, 0xc8207b5200, 0x0, 0x0, 0x0)
	/home/arthurprs/godev/src/github.com/jinzhu/gorm/preload.go:160 +0x8f4
github.com/jinzhu/gorm.Preload(0xc82079ec00)
	/home/arthurprs/godev/src/github.com/jinzhu/gorm/preload.go:67 +0xba5
github.com/jinzhu/gorm.(*Scope).callCallbacks(0xc82079ec00, 0xc820145520, 0x3, 0x4, 0xc82079ec00)
	/home/arthurprs/godev/src/github.com/jinzhu/gorm/scope_private.go:331 +0x68
github.com/jinzhu/gorm.(*DB).Find(0xc8207ba500, 0x8685c0, 0xc820799fa0, 0x0, 0x0, 0x0, 0xc8207ba500)
	/home/arthurprs/godev/src/github.com/jinzhu/gorm/main.go:215 +0xb3
github.com/jinzhu/gorm_test.TestNestedPreload2(0xc820011170)
	/home/arthurprs/godev/src/github.com/jinzhu/gorm/preload_test.go:188 +0xace
testing.tRunner(0xc820011170, 0xec6f18)
	/home/arthurprs/.gvm/gos/go1.5.1/src/testing/testing.go:456 +0x98
created by testing.RunTests
	/home/arthurprs/.gvm/gos/go1.5.1/src/testing/testing.go:561 +0x86d
```

If I change `got` variable to be of type `Level3` it works though

**Comment by lscieux** [comment]
PR https://github.com/jinzhu/gorm/pull/836 is fixing that

**Comment by arthurprs** [comment]
Awesome!

**Comment by jinzhu** [comment]
Merged that pull request, thanks @lscieux's contribution
