### ISSUE TITLE
Migrate failed in the case of having interface field in struct.

### ISSUE THREAD

**Issue by kotakanbe** [jinzhu/gorm#870]
Migrate failed in the case of having interface field in struct.
Does this usage is supported?

* go: go version go1.6 darwin/amd64
* gorm: origin/master
* Sqlite3:  3.8.10.2 2015-05-20 18:17:19 2ef4f3a5b1d1d0c4338f8243d40a2452cc1f7fe4

code
```go
package main

import (
        "fmt"

        "github.com/jinzhu/gorm"
        _ "github.com/mattn/go-sqlite3"
)

type Man struct {
        gorm.Model
        Name   string
        Phone Phone
}

type Phone interface {
        Call(string)
}

type IPhone struct {
        gorm.Model
        Version string
        Price   string
}

func (p IPhone) Call(number string) {
        fmt.Printf("[iPhone] call %s\n", number)
}

type Android struct {
        gorm.Model
        Version string
}

func (p Android) Call(number string) {
        fmt.Printf("[Android] call %s\n", number)
}

func main() {
        db, err := gorm.Open("sqlite3", "./db.sqlite3")
        if err != nil {
                panic(err)
        }

        db.LogMode(true)

        if err := db.AutoMigrate(
                &Man{},
                &IPhone{},
                &Android{},
        ).Error; err != nil {
                panic(err)
        }
}
```
console
```
(<autogenerated>:117)
[2016-02-27 21:01:42]  [0.59ms]  SELECT count(*) FROM sqlite_master WHERE type='table' AND name='men'
panic: invalid sql type Phone (interface) for sqlite3

goroutine 1 [running]:
panic(0x4293da0, 0xc82045e1b0)
        /usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/jinzhu/gorm.sqlite3.SqlTag(0x42cf6c0, 0xc82045e180, 0x194, 0xff, 0xc820439700, 0x0, 0x0)
        /Users/kotakanbe/go/src/github.com/jinzhu/gorm/sqlite3.go:43 +0x3b4
github.com/jinzhu/gorm.(*sqlite3).SqlTag(0x4443840, 0x42cf6c0, 0xc82045e180, 0x194, 0xff, 0x0, 0x0, 0x0)
        <autogenerated>:116 +0xca
github.com/jinzhu/gorm.(*Scope).generateSqlTag(0xc820128e00, 0xc8203b40d0, 0x0, 0x0)
        /Users/kotakanbe/go/src/github.com/jinzhu/gorm/model_struct.go:558 +0x670
github.com/jinzhu/gorm.(*Scope).createTable(0xc820128e00, 0xc820128e00)
        /Users/kotakanbe/go/src/github.com/jinzhu/gorm/scope_private.go:554 +0x10d
github.com/jinzhu/gorm.(*Scope).autoMigrate(0xc820128e00, 0xc820128e00)
        /Users/kotakanbe/go/src/github.com/jinzhu/gorm/scope_private.go:637 +0x10f
github.com/jinzhu/gorm.(*DB).AutoMigrate(0xc8201132c0, 0xc820439e68, 0x3, 0x3, 0x1)
        /Users/kotakanbe/go/src/github.com/jinzhu/gorm/main.go:428 +0xc7
main.main()
        /Users/kotakanbe/tmp/gorm_interface.go:51 +0x3d4
exit status 2
```

**Comment by jinzhu** [comment]
@kotakanbe gorm doesn't know how to create table for the field, it has to be a `Scanner`, `Valuer` for customized field type.

**Comment by kotakanbe** [comment]
@jinzhu 

thanks!!
I changed my code as below.

```go
package main

import (
        "fmt"

        "github.com/jinzhu/gorm"
        _ "github.com/mattn/go-sqlite3"
)

type Man struct {
        gorm.Model
        Name    string
        IPhone  IPhone
        Android Android
}

type Phone interface {
        Call()
}

type IPhone struct {
        gorm.Model
        ManID uint

        Number  string
        Version string
        Price   string
}

func (p IPhone) Call() {
        fmt.Printf("[iPhone] call %s\n", p.Number)
}

type Android struct {
        gorm.Model
        ManID uint

        Number  string
        Version string
}

func (p Android) Call() {
        fmt.Printf("[Android] call %s\n", p.Number)
}

func main() {
        db, err := gorm.Open("sqlite3", "./db.sqlite3")
        if err != nil {
                panic(err)
        }

        //  db.LogMode(true)

        if err := db.AutoMigrate(
                &IPhone{},
                &Android{},
                &Man{},
        ).Error; err != nil {
                panic(err)
        }

        man := Man{
                Name:    "kojimayoshio",
                IPhone:  IPhone{Number: "0120-117-117", Version: "6s", Price: "$300"},
                Android: Android{Number: "0120-0930", Version: "KitKat"},
        }
        db.Create(&man)

        yoshio := Man{}
        db.Where(Man{Name: "kojimayoshio"}).First(&yoshio)

        iphone := IPhone{}
        db.Model(&yoshio).Related(&iphone)
        yoshio.IPhone = iphone

        android := Android{}
        db.Model(&yoshio).Related(&android)
        yoshio.Android = android

        phones := []Phone{
                yoshio.IPhone,
                yoshio.Android,
        }
        for _, phone := range phones {
                phone.Call()
        }

}
```
