### ISSUE TITLE
Polymorphic slice of pointers

### ISSUE THREAD

**Issue by stroborobo** [jinzhu/gorm#988]
Hi!

Apparently it's not possible to use pointer slices for polymorphism, just plain slices. Is that intended?

So this works:

```go
type struct ShopCountdown struct {
	// ID etc
	Countdowns []Countdown `gorm:"polymorphic:Owner;"`
}
```

But this crashes:

```go
type struct ShopCountdown struct {
	// ID etc
	Countdowns []*Countdown `gorm:"polymorphic:Owner;"`
}
```

```
goroutine 167 [running]:
panic(0x6008c0, 0xc82000a170)
        /usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:481 +0x3e6
github.com/jinzhu/gorm.(*Scope).GetModelStruct.func1(0xc820180080, 0xe, 0x10, 0xc820180000, 0xe440a8, 0x68f820, 0xc820a38060, 0xc820a380c0)
        /Users/bo/src/go/src/src.ybit.eu/ybit/discountdown/Godeps/_workspace/src/github.com/jinzhu/gorm/model_struct.go:217 +0x7df
created by github.com/jinzhu/gorm.(*Scope).GetModelStruct
        /Users/bo/src/go/src/src.ybit.eu/ybit/discountdown/Godeps/_workspace/src/github.com/jinzhu/gorm/model_struct.go:393 +0xc85
```

**Comment by stroborobo** [comment]
Seems to be resolved.

**Comment by thomaswelton** [comment]
When was this resolved? I'm getting the same issue

**Comment by thomaswelton** [comment]
Yeah, not an issue with gorm. This is supported.
I was using make to create a slice of a fixed size that was too large.
